# Generated by Django 2.0.4 on 2018-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20180612_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='church',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
